name: ocr
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.2.*+cu121 torchvision==0.17.* torchaudio==2.2.* --index-url https://download.pytorch.org/whl/cu121
      - flash-attn
      - bitsandbytes
      - git+https://github.com/huggingface/transformers
      - accelerate
      - qwen-vl-utils[decord]==0.0.8
      - flask
      - pillow
      - pymupdf
